# Generated by Django 5.1.7 on 2025-03-27 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_groups_alter_customuser_telefone_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos aos quais o usuário pertence.', related_name='customuser_groups', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nome_completo',
            field=models.CharField(max_length=150, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido. O formato deve conter até 15 dígitos e pode incluir "+" no início.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='customuser_permissions', to='auth.permission', verbose_name='Permissões de usuário'),
        ),
    ]
